#!/usr/bin/env bash
# script uses scp to copy
if (($# < 4))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostkeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
